- models/openoil.py
If you are interested in making seed_from_gml work for newer versions of matplotlib Knut-Frode.
> Small tweek in seed_from_gml to make it work with matplotlib after 1.2.0

- readers/reader_ROMS_native.py
This fixes a bug with reading the hc parameter from netcdf (see below). 
```
======================================================================
ERROR: test_interpolation_missing (readers.test_interpolation.TestInterpolation)
Test interpolation.
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\Users\anbro\Documents\projects\opendrift\readers\test_interpolation.py", line 225, in test_interpolation_missing
'/../test_data/2Feb2016_Nordic_sigma_3d/Nordic-4km_SLEVELS_avg_00_subset2Feb2016.nc')
File "C:\Users\anbro\Documents\projects\opendrift\readers\reader_ROMS_native.py", line 94, in __init__
self.hc = self.Dataset.variables['hc'][:]
File "netCDF4.pyx", line 2814, in netCDF4.Variable.__getitem__ (netCDF4.c:35116)
TypeError: …
```
> Fixed bug in roms reader when reading the hc parameter

- opendrift/readers/reader_ROMS_native.py
Instead of assuming Vtransform = 1 as per default in sdepth()
Using `np.asarray(self.Dataset['Vtransform'])` seems to work whether the "Dataset" is loaded using netCDF4 or xarray.
> Read Vtransform from native ROMS files

- opendrift/__init__.py
The following was needed to use the open() subfunction 
#from models import oceandrift3D
#cls = oceandrift3D.OceanDrift3D
from opendrift.models import oceandrift
cls = oceandrift.OceanDrift
> updating model name to oceandrift in open() function

- opendrift/models/basemodel.py
- allow to define a subgrid (domain) for the calculation of LCS
- allow to calculate LCS with particles seeded at specified depth
- introduce switch to deactivate plotting of initial particle positions in o.plot. This is useful to check if LCS calculations are realistic.
At present, calculate_ftle uses the map projection of a specified reader. Code could be expanded to also allow the user to provide a proj4 string og pyproj object.
Note that LCS does not work well for fake projections (reader_ROMS_native)
> allow selection of sub-domain for LCS calculation

- opendrift/models/oceandrift.py
Add a call to bottom_interaction() in vertical_buoyancy() so that the check for particle on or below seabed is done even when vertical_mixing is switched off.
> Run bottom_interaction() in vertical_buoyancy()

- opendrift/models/oceandrift.py
Adding a new option for `vertical_mixing:diffusivitymodel` = 'constant'. where the fallback value is used.
> Allow for constant 'ocean_vertical_diffusivity' values

- opendrift/readers/basereader/continuous.py
- opendrift/readers/basereader/structured.py
- opendrift/readers/basereader/unstructured.py
- opendrift/readers/basereader/variables.py
- opendrift/readers/interpolation/structured.py
- pytest.ini
- tests/integration/test_readers.py
- reader: unwrap get_variables_impl and get_variables_derive
- pytest: register slow and veryslow marks
> Unwrap get_variables_wrapper (impl) + get_variables_derived so that these are not called back from sub-class

- opendrift/readers/basereader/structured.py
- tests/unit/basereader/test_structured.py
@knutfrode : I don't think we need the try/except logic anymore. It is not any more risky than the other code, and should work on all platoforms without further ado as far as I can see. Do you remember why it was there in the first place?
> structured: remove try/except for lonlat2xy parallel. __disable_parallel__ is used to disable parallel lonlat2xy

- opendrift/readers/reader_netCDF_CF_generic.py
The part of the grid corresponding to the active particles is calculated using xmin and ymin, but this should be x[0] and y[0]. For coordinates in decreasing order the minimum is not the same as the first value and the wrong part of the grid would be loaded. The use of np.abs here avoids having to use a signed delta_x and delta_y, which could break code in other places.
> reader_netCDF_CF_generic: bugfix for lazy loading with coordinates in decreasing order

- opendrift/models/basemodel.py
since __save_animation() is now called from __save_or_plot_animation()
> stack_offset 3 ->

- examples/example_oil_ice.py
- opendrift/models/basemodel.py
- opendrift/models/oceandrift.py
Without this fix elements were being deactivated at the end of the mixing loop and "freezing" slightly above seafloor
> vertical_mixing: reflect particles from seafloor only if they are not supposed to be deactivated

- opendrift/readers/reader_netCDF_CF_generic.py
Added functionality to the reader to chose which ensemble member should be used when working with ensemble data. 
Added an argument in the function call called "ensemble_member", which defaults to None. This argument takes in an integer. 
Added a if statement when initially reading in the data, which checks if the "ensemble_member" argument has been used, and if it has, then it will read in data from that specific ensemble member using xarrays .isel() option.
> Added option to chose ensemble member in reader_netCDF_CF_generic.py

- opendrift/models/basemodel.py
-fixing a small bug, white line around legend markers when rendering animation with fast=True
-new functionality for manually deactivating/ignoring some specific legend labels
> animation legend modifications

- opendrift/export/io_netcdf.py
for some reason numpy.ma.array allocation is extremely slow when mask=True is passed
> Speeding up allocation of self.history in import_file

- opendrift/models/physics_methods.py
- tests/models/test_physics.py
- tests/models/test_run.py
- tests/models/test_stranding.py
and avoid discontinuity at depth==MLD
should be ready to merge if you guys agree
this is just a small linearly increasing correction factor, which is 0 at depth=0, and gradually increasing to background_diffusivity when depth==MLD.
This discontinuity caused problems in some cases
> correction factor to make diffusivity profile approach background diffusivity at depth==MLD

- opendrift/models/sedimentdrift.py
I just spent way too much time figuring out why my particles always ended up at -0.01 depth. Turns out the default depth of the SedimentDrift module is 0, which is not very helpful.
> Set same default ocean floor depth in SedimentDrift as in OceanDrift

- opendrift/readers/basereader/structured.py
- opendrift/readers/reader_ROMS_native.py
I made changes to structured.py to allow for saving the interpolators to save time on repeated simulations. The necessary attributes to use the save option need to be input via the reader, currently only available in the ROMS reader.
This PR also has changes that clean up the name variable in the ROMS reader. Previously there was logic to deal with name for several cases but subsequently it was overwritten to be “roms native”. Now name is used if input and otherwise set to “roms native”.
The change to allow for saving interpolators was mentioned in https://github.com/OpenDrift/opendrift/issues/1130.
> Allow for saving of interpolators

- opendrift/models/basemodel/__init__.py
there was a bug writing data to the netCDF file. In some rare situations, step 100 (the default) is skipped, leading to an error as the buffer_limit _length is exceeded in the next step.
The following code produce the error :
`from datetime import datetime, timedelta
from opendrift.models.oceandrift import OceanDrift
o = OceanDrift(loglevel=20)
o.set_config("general:use_auto_landmask", False)
o.set_config("environment:constant:land_binary_mask", 0)
o.set_config("drift:max_age_seconds", 100)
start_time = datetime(2024, 1, 1)
o.seed_elements(lon=3, lat=60, time=start_time)
o.seed_elements(lon=3, lat=60, time=start_time + timedelta(hours=1) * 7)
o.seed_elements(lon=3, lat=60, time=start_time + timedelta(hours=1) * 100)
o.run(
steps=200,
export_buffer_length=5,
outfile="test.nc", …
> state_to_buffer save

- environment.yml
- opendrift/export/io_parquet.py
- tests/models/test_io.py
For long-running simulations with limited particle lifetimes, in-memory sizes of netcdf arrays become quite large. Also, (at least for me) the first operation I do with the netcdf files usually is `xr.open_dataset(...).to_dataframe()`.This is a first draft that writes directly to a tabular format.
> IO module for parquet

- opendrift/models/basemodel/__init__.py
- opendrift/models/chemicaldrift.py
- opendrift/models/larvalfish.py
- opendrift/models/model_template.py
- opendrift/models/oceandrift.py
- opendrift/models/openberg.py
- opendrift/models/openhns.py
- opendrift/models/openoil/openoil.py
- opendrift/models/pelagicegg.py
- opendrift/models/physics_methods.py
- opendrift/models/plastdrift.py
- opendrift/models/radionuclides.py
- opendrift/models/sealice.py
- opendrift/models/sedimentdrift.py
- opendrift/readers/basereader/consts.py
- opendrift/readers/reader_ROMS_native.py
- tests/models/test_run.py
- tests/models/test_stranding.py
- tests/readers/test_depth.py
- tests/readers/test_netcdf.py
- tests/readers/test_roms.py
* added sea_surface_height to OceanDrift and models that subclass OceanDrift, also a new parameter
* interact_with_seafloor accounts for zeta in bottom check, as does other bottom check in OceanDrift
* angle and zeta are updated in ROMS reader
* z_rho calculation is shifted so that it is 0 at the surface like z 
* tests are updated, including a ROMS reader specific test file
* changed sea_floor_depth_below_sea_level to -20 from -10 for wet/dry cases that are a little more extreme
> Updates to ROMS zeta, seafloor checks, tests

- opendrift/models/basemodel/__init__.py
Hi @knutfrode , @johannesro 
Opening up a PR for review/discussion on this. 
In the FTLE computation, one needs to calculate the displacement from each initial position (X,Y), that are then fed to `ftle()`. 
It seems that opendrift inverts the order of (lon,lat) when run in backwards mode. So doing this below, would return `b_x1,b_y1` matrices that are not ordered the same way as X and Y. 
```                
b_x1, b_y1 = proj(o.history['lon'].T[-1].reshape(X.shape),o.history['lat'].T[-1].reshape(X.shape))
```
This means that when doing this `b_x1-X` it's not substracting the correct initial positions from the final positions. Flipping the final (lon,lat) arrays seems to yield a consistent matrix ordering, and so correct net displacements fed to `ftle`
```                
b_x1, b_y1 = …
```
> Possible bug in LCS computation ?

- opendrift/models/basemodel/__init__.py
- opendrift/models/oceandrift.py
- opendrift/readers/reader_ROMS_native.py
Fix z_rho in ROMS reader: z_rho in the ROMS reader could be greater than 0 for wet/dry scenarios when in a dry area. When this happens, z_rho is now changed to nan instead.
Removed dcrit: Previously I had added a parameter to opendrift, dcrit, which was added to the sea surface height as a minimum value in wet/dry cells. However, I have now realized I misinterpreted the ROMS docs on this issue and it should not be present. Therefore, I have removed it from opendrift entirely.
> fix z_rho and remove dcrit

- Dockerfile
The environment.yml and thus the dependencies are completely fine apparently, but the mamba dependency solver is horrible, and so it fails.
Switching to micromamba has completely fixed the issue, and should make dependency fetching faster and more stable.
> fixed docker builds by migrating to micromamba

- opendrift/readers/reader_schism_native.py
In file: reader_schism_native.py, method: `interpolate`, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not have identity and will match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. 
The following binary operation
```profiles is not []```
compares a newly created object with the identity operator which will always evaluate to True.
I suggested that the logical operation should be reviewed for correctness. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation …
> Remove a logical short circuit in a test expression

- opendrift/models/basemodel/environment.py
To me, the current log info for the default landmask is very confusing. The `reader_global_landmask` module does not even mention `config:drift_max_speed`.
> clarify log info for default landmask

- opendrift/models/basemodel/__init__.py
- opendrift/readers/reader_shape.py
Hi, I've had a round with the detection of closest ocean points. For shape readers, this is pretty easy, see this PR. I assume there are some things to fix but wanted to hear your ideas first. I am also unsure about using a global config argument for the buffer, and how to name it.
Also attaching a before/after plot where the current PR keeps particles from "tunneling" through narrow pieces of land. @mateuszmatu might have some more detailed plots of what the current algorithm's helper grid looks like for such cases.
Before:
After:
> [draft] improved closest ocean points for shape readers

- opendrift/export/io_netcdf.py
faster loading of large opendrift output files. In the earlier version, manual indexing with np.arange(num_elements) and index_of_last would trigger a complete materialization of the self.result[var]. This version allows lazy loading with Dask. 
AI recommended. Human check welcome. Potential drawbacks?
> Optimized trajectory indexing in import_file
