OpenDrift/opendrift

- readers/reader.py
- readers/reader_ROMS_native.py
Hi. I added rotation of wind vectors in the native ROMS reader
> Rotation of wind

- models/oceandrift.py
As suggested by Knut-Frode; age was added to the opendrift particles, so they could be deactivated after a certain time.
> Added deactivation of elements after a certain time

- opendrift/models/basemodel.py
- opendrift/models/opendrift3D.py
- opendrift/models/openoil.py
- opendrift/models/openoil3D.py
- opendrift/readers/reader_ROMS_native.py
Include functionality for using T,S profiles in mixing inner loop,
and a few bugfixes
> Revisit 3dmixing

- examples/example3d.py
- examples/example_codegg.py
- opendrift/models/oceandrift3D.py
- opendrift/models/opendrift3D.py
- opendrift/models/openoil3D.py
- opendrift/models/pelagicegg.py
- opendrift/readers/reader_ROMS_native.py
This should be mature for merging, the vertical advection has been tested with ROMS input. Interaction with bottom may need revision.
> Verticaladvection

- opendrift/models/basemodel.py
- opendrift/models/eddydiffusivity.py
- opendrift/models/opendrift3D.py
- opendrift/models/openoil.py
- opendrift/models/openoil3D.py
- opendrift/models/physics_methods.py
Implemented new mixing scheme based on non-discrete random walk. Tests need to be adopted.
> New visser mixing

- opendrift/models/openoil.py
- tests/test_oillibrary.py
Biodegradation function based on Adcroft *et al.* (2010), "*Simulations of underwater plumes of dissolved oil in the Gulf of Mexico*".
> Biodegradation 

- conda_python2_oil.yml
- conda_python3.yml
- requirements.txt
> Use OpenDrift oil fork

- opendrift/readers/reader_netCDF_CF_generic.py
- opendrift/readers/reader_netCDF_CF_unstructured.py
* Attempt to use xarray in reader_netCDF_CF_generic
* Included false_easting/false_northing when handling polar stereographic projection
* Some changes in reader_netCDF_CF_unstructured to set interpolation buffer by arguments
> Reader mod

- .travis.yml
- examples/example.py
- examples/example_LCS_norkyst.py
- examples/example_coastline.py
- examples/example_coastline_options.py
- examples/example_diffusion.py
- examples/example_ensemble.py
- examples/example_leeway_cone.py
- examples/example_oil_ice.py
- examples/example_oil_thickness.py
- examples/example_plast.py
- examples/example_radionuclides.py
- examples/example_reader_boundary.py
- examples/example_seed_demonstration.py
- examples/example_shipdrift.py
- opendrift/models/basemodel.py
- opendrift/models/openoil.py
- opendrift/readers/reader_global_landmask.py
- opendrift/scripts/opendrift_gui.py
- testall
- tests/benchmarks/performance_test_oil.py
- tests/conftest.py
- tests/integration/test_netcdf.py
- tests/integration/test_plot.py
- tests/integration/test_readers.py
- tests/integration/test_run.py
- tests/integration/test_stranding.py
- tests/unit/test_global_landmask.py
- tests/unit/test_global_landmask_basemap.py
- tests/wps/wps_test.py
(Currently depends on #145, but does not need to)
Not all old functionality has been moved yet.
> Use cartopy for plotting

- opendrift/readers/reader_netCDF_CF_generic.py
@knutfrode: can you check if the examples I suggest make sense?
> document netcdf reader

- opendrift/readers/__init__.py
> reader: use full mod name

- environment.yml
- tests/integration/test_netcdf.py
- tests/unit/test_netcdf.py
Unidata/python-netcdf4#982 seems to be fixed.
> relex netcdf requirements

- .gitignore
- examples/example_interpolation.py
- examples/example_radionuclides.py
- opendrift/models/radionuclides.py
Rebased version of #253. @magnesim could you please check if this is correct?
> Radionuclide

- examples/example_shape_landmask.py
- opendrift/readers/reader_shape.py
- tests/unit/test_reader_shape.py
> reader_shape: read land shapes from shapefiles

- tests/integration/test_models.py
unit-tests for the oil-in-ice module
> unit-tests for oil-in-ice

- opendrift/models/basemodel.py
elaborating on calculate_ftle; allow custom projections to be passed by user.
> allow proj object or string to be passed to calculate_ftle

- chemicaldrift.py
Created new class to be used in EMERGE project for drifting of chemicals emissions from marine traffic
> new ChemicalDrift class

- environment.yml
- opendrift/models/basemodel.py
> use coloredlogs for .... colored logs!

- opendrift/models/basemodel.py
- opendrift/version.py
Useful since many users run opendrift from source repository.
> version: log git version if available

- docs/source/choosing_a_model.rst
- docs/source/conf.py
- opendrift/__init__.py
- opendrift/models/basemodel.py
- opendrift/models/openoil.py
- opendrift/models/radionuclides.py
- opendrift/readers/__init__.py
- opendrift/readers/basereader/__init__.py
- opendrift/readers/basereader/continuous.py
- opendrift/readers/basereader/structured.py
- opendrift/readers/basereader/unstructured.py
- opendrift/readers/basereader/variables.py
- opendrift/readers/reader_netCDF_CF_unstructured.py
- correctly import pyproj
- document: readers
- test: remove old unittest timer fixture
> docs readers

- .circleci/config.yml
* Cache blir brukt på PR dersom ingen eksempel har blitt endra
* Legg inn `[run-ex]` i tittel på PR for å tvinge ny køyring
* Eksempel blir alltid bygd på nytt på master.
Ref:  https://github.com/OpenDrift/maintenance/blob/master/dev/testing.md
> [run-ex] get github pr title in docs-build

- .circleci/config.yml
- opendrift/readers/basereader/structured.py
- opendrift/readers/basereader/variables.py
- tests/unit/basereader/test_structured.py
- structured: re-write par processing of lonlat2xy. increase par cutoff to 10.000.
- structured: lonlat2xy: test big dataset
> par lonlat2xy

- opendrift/models/radionuclides.py
Fix bug with positive z-values in desorption
> Check if z>0, put down to ocean

- examples/example_shipdrift.py
- opendrift/models/basemodel.py
- opendrift/models/chemicaldrift.py
plus some small upgrades in chemicaldrift
> customizable legend in baseline animation method

- opendrift/models/chemicaldrift.py
- opendrift/readers/basereader/__init__.py
Adding SPM concentration environmental variable and dynamic update of sorption rates according to SPM concentration.
Fixing dynamic update of desorption rates with sea water temperature and salinity.
Ready to merge
> Added SPM concentration. Fixed correction factors for sorption/desorption rates

- .circleci/config.yml
- tests/readers/test_reader_shape.py
- shape reader: skip if NE shapes are missing
- ci: trigger new deps install
> shape tests

- .circleci/wake-up-thredds.py
- opendrift/readers/reader_schism_native.py
- tests/readers/test_schism_native.py
@simonweppe : this removes the dependency on future, take a look at the tests. ideally this file should be extended with more tests.
> schism: remove depenency on future + add a couple of tests

- .circleci/config.yml
- docs/Makefile
- docs/source/conf.py
- ci/docs: store test artifacts
- docs: sharded examples
- ci: build examples sharded
> [run-ex] ci docs junit

- examples/example_chemicaldrift.py
- opendrift/models/chemicaldrift.py
> chemicaldrift gallery example

- opendrift/models/chemicaldrift.py
> Emission factors for more chemicals, and comments

- examples/example_oilspill_seafloor.py
- opendrift/models/oceandrift.py
should be ready to merge
Tested on
example_oil_verticalmixing.py
example_codegg.py
example_vertical_mixing.py
example_oilspill_seafloor.py
> Improving speed and bugfix in animate_vertical_distribution() 

- opendrift/models/sealice.py
- tests/models/test_sealice.py
2021-06-21 5d629b2b julien introduced vertical mixing
2021-06-18 0160dcbf julien Debugging reader selafin the lice are now able to sense and move vertically There is a memory leak
2021-06-18 84afb9a7 julien Functional superindividuals actively swimming towards light and sinking at night
2021-06-17 f4f2a82e julien first successful loading no run yet
2021-06-16 260911ce julien Modification of variables in sea lice model minor other fiel editions
2021-06-16 4b1b1a66 julien New method for parametrisation Not working
2021-06-16 199dc25b julien use of add_config to setup the parameters Use the biomass in elements and compute the population based on proportions of the reference population (linear relation)
2021-06-16 266abf90 julien first try
> add sealice model

- examples/example_grid.py
- opendrift/export/punkrockwriters.py
should be ready to merge.... althogh not testet for matplotlib < 3.4
> switch Matplotlib version punkrockwriters 

- opendrift/models/basemodel.py
> just logging info to check which backend is used in Sphynx-gallery CircleCI

- .circleci/config.yml
- opendrift/models/basemodel.py
- ci: revert specify MPLBACKEND
- basemodel: cleanup debug output for save animation
> cleanup debug

- opendrift/models/basemodel.py
> basemodel: fix for animations not working in interactive mode

- opendrift/models/basemodel.py
- opendrift/models/oceandrift.py
Setting blit=False in some cases
> Fix for animation_profile() and animate_vertical_distribution() in interactive mode

- opendrift/models/oceandrift.py
(no performance difference on example_mixed_layer_depth for 7 days simulation. Not tested eventual performance difference for 100000 particles yet)
> vertical_mixing: fix for depths below -255m

- examples/example_chemicaldrift.py
- opendrift/models/chemicaldrift.py
mostly house cleaning with two small new features. Ready to merge.
> ChemicalDrift updates

- examples/example_chemicaldrift.py
- opendrift/models/chemicaldrift.py
integration of method and updating gallery example
> ChemicalDrift: Integration of method for plotting chemical mass distribution

- opendrift/models/chemicaldrift.py
DOC concentration vertical profile, dissolved/particles initial fraction
ready to merge
> ChemD updates

- opendrift/models/chemicaldrift.py
> ChemD updates: fOC, KOC from user, sediments leaking rate

- opendrift/models/chemicaldrift.py
> ChemD: more emission factors for PAHs and metals from scrubbers

- opendrift/models/chemicaldrift.py
> activating emission factors for closed loop scrubbers

- examples/example_chemicaldrift.py
- opendrift/models/chemicaldrift.py
> rename POC to SPM

- opendrift/models/chemicaldrift.py
> ChemD: updates in method to generate gridded concentration maps

- opendrift/models/chemicaldrift.py
> ChemD: write_netcdf_chemical_density_map, support readers without time

- opendrift/models/chemicaldrift.py
> ChemD: enabling modelling of metals using transfer_setup==Bokna_137Cs

- opendrift/models/chemicaldrift.py
> ChemD: adding support for ionizing organics

- opendrift/models/chemicaldrift.py
> ChemicalDrift code cleaning

- opendrift/models/openoil/openoil.py
Hi there, please consider these changes - I think they may be important for subsea releases
> a couple of bugs in openoil's update_terminal_velocity()

- opendrift/models/chemicaldrift.py
> ChemD: seeding fixes

- opendrift/models/chemicaldrift.py
> ChemD: write_netcdf_chemical_density_map improvements

- opendrift/models/chemicaldrift.py
> removing parentheses from chemicals name

- opendrift/models/chemicaldrift.py
> removing parentheses from ALL chemicals names

- opendrift/models/chemicaldrift.py
> emission factors from additional scrubbers chemicals and other ship discharges

- opendrift/models/chemicaldrift.py
> ChemD: distribution coefficients for some metals + salinity dependency

- opendrift/models/chemicaldrift.py
- opendrift/models/radionuclides.py
'.seconds' does not work for time_step >= 24 hours. Changed to '.total_seconds()'
@magnesim 
ready to merge I think
> ChemD+RadioN: Bugfix. '.seconds' to to '.total_seconds()'

- opendrift/models/chemicaldrift.py
- tests/models/test_chemicaldrift.py
first ChemicalDrift test.
5s. Too slow? 
Seems to be impossible to make a ChemicalDrift simulation less then 3s.....
ready to merge
> ChemD: unit testing - dynamic partitioning

- opendrift/models/chemicaldrift.py
> Writing concentration files with customized landmask from shape file

- examples/example_radionuclides.py
Read lat and lon using get_variables function,
Set new max and min locations
> Fix creation of concentraiton output file

- opendrift/models/chemicaldrift.py
> ChemD: origin_marker as parameter when writing concentration maps files

- opendrift/models/chemicaldrift.py
> ChemD: Bugfix Concentrations by origin_marker

- opendrift/models/chemicaldrift.py
> ChemD: adding more PAHs

- opendrift/models/basemodel/environment.py
- opendrift/readers/reader_lazy.py
I've modified two files to allow lazy_reader passing zarr auth info to netcdf reader. Please let me know if it breaks anything.
> Allow lazy loading zarr dataset via netcdf reader

- opendrift/readers/reader_lazy.py
- opendrift/readers/reader_netCDF_CF_generic.py
A small detail was missing in https://github.com/OpenDrift/opendrift/pull/1193
I created a new variable in LazyReader, to hold on to the dataset (self._dataset). This is due to a "hack" in netcdf class where the variable filename can be a string OR a dataset, so I'm not the only one to blame for this being a bit custom. Shall I include more comments in the code to make it understandable?
> Addition to pullrequest 1193

- opendrift/models/larvalfish.py
* added stokes x/y velocity variables to required variables
* added stokes function to LarvalFish update method so it is run
> Changes to LarvalFish so Stokes can be modeled

- opendrift/models/openberg.py
Updated_Openberg_Physics presentation
> Updated_Openberg_Physics presentation

- opendrift/models/chemicaldrift.py
> ChemD fixes

- opendrift/readers/reader_ROMS_native.py
Main changes are to allow for the land_binary_mask as well as mask_rho, mask_u, and mask_v to have 3D or 2D dimensions since masks in ROMS can vary in time if they represented cells that can wet and dry in time. With the changes, if a variable `wetdry_mask_rho` is available, it will be used for the rho mask in place of `mask_rho`, otherwise will use `mask_rho`, and the same for the u and v masks. The masks for different grids use the same indices, same as before these changes, but now they are managed a little more simply in one location in the function. Additionally, more effort is made to match variables to the appropriate mask since sometimes they may not be a typical ROMS- output variable.
More changes:
* masks are saved in a dict in case they are reused across different variables
* …
> changes to ROMS reader for wetdry masks

- opendrift/readers/basereader/structured.py
- opendrift/readers/reader_ROMS_native.py
I had the interpolator save and reuse working but did not realize it was not using the path I entered through the ROMS reader. I realized now that I called the interpolator filename variable two different things! I have fixed this now and also modified a few logger messages to be clearer.
> Typo fix to connect ROMS reader to save interpolator

- examples/example_macondo.py
- opendrift/models/basemodel/__init__.py
this should be ready to merge.
this works also without selecting a subset of output frames with o.run, which is undesired in some cases
> fast and small animation files by selecting frames as range or list

- opendrift/models/basemodel/__init__.py
Now you can specify a precision value in degrees to which the particles get their position approximated to the coastline whenever they get stranded.
So we're going from this:
To this:
At barely any cost! 😁
> New coastline interaction functionality implemented

- examples/example_openberg_new.py
- opendrift/models/openberg.py
Updated openberg module and example
> #1341 updated icebergs module

- opendrift/readers/operators/ops.py
- opendrift/readers/operators/readerops.py
General modification: modify reader_ops to add the possibility for reader_b to be a list of readers.
Gaussian changes : modify reader_ops and ops to change the operator function defined in ops from gaussian melting to only gaussian factor. The end of the calculation in done by hand, depending on the case.
Maybe we should keep only one representation now, by inserting a reader in a list if it's the only one that is given during the definition. That would allow us to keep only the branches with the lists in the code, making it clearer.
It is also needed to make the code about the profiles combination in reader_ops, I was not understanding what is needed here. I think it is strange to apply any operation on profiles.
> Addinf the possibility to combine many readers all at once

- opendrift/models/sedimentdrift.py
Current code cannot run SedimentDrift simulation with constant ocean vertical diffusivity. resolves #1392
> sets 'profiles' to True for 'ocean_vertical_diffusivity'

- opendrift/models/openberg.py
corrected version of the openberg module
> corrected version of the openberg module

- opendrift/models/basemodel/__init__.py
- re-raise error if iomodule cannot be imported
- bm: remove unused vars
> io dataset

- .circleci/config.yml
- .gitignore
- pyproject.toml
- yapf: don't allow splitting dict values
- yapf: format basemodel
> formating and remove poetry

- opendrift/models/chemicaldrift.py
self.get_property to self.result
ready to merge
> ChemD: updating write_netcdf_chemical_density_map to self.result

- opendrift/models/chemicaldrift.py
> ChemD: fixes in plot_mass method

- opendrift/models/chemicaldrift.py
can later be moved to post_run()
ready to merge
> ChemD: Saving custom attrs to self.result and refer to these in postprocessing

- opendrift/models/chemicaldrift.py
> ChemD: fix for custom variables to be saved in self.result

- opendrift/models/chemicaldrift.py
- tests/models/test_chemicaldrift.py
more chemicaldrift tests
preventing a warning
ready to merge
> ChemD: more chemicaldrift tests and preventing a warning in degradation method

- tests/models/test_chemicaldrift.py
improving test_chemicaldrift.py
ready to merge
> ChemD: adding test for write_netcdf_chemical_density_map

- opendrift/models/chemicaldrift.py
removing old fix
this was due to erroneous 0 values in some old shyfem datasets
better to change/filter the input datasets if the problem still exists
ready to merge
> ChemD: removing old temporary fix for 0 values in shyfem datasets

- opendrift/readers/reader_ROMS_native.py
> ROMS: use ln_AKs instead of AKs (useful for Norkyst and Norfjords v3)

- environment.yml
- examples/example_multiprocessing.py
> Adding gallery example of parallel execution in multiple CPUs
